name: TMBBau
version: 1.0
author: XenoDEV
api-version: 1.16

main: me.xenodev.tmbt.main.Main

commands:
  gm:
    description: Setze den Gamemode eines Spielers um
  gamemode:
    description: Setze den Gamemode eines Spielers um
  sign:
    description: Signiere ein Item in deiner Hand
  signate:
    description: Signiere ein Item in deiner Hand
  oz:
    description: Schaue die Onlinezeit eines Spieler an
  ot:
    description: Schaue die Onlinezeit eines Spieler an
  onlinezeit:
    description: Schaue die Onlinezeit eines Spieler an
  onlinetime:
    description: Schaue die Onlinezeit eines Spieler an
  rename:
    description: Nenne ein Item in deiner Hand um
  changelog:
    description: Schaue dir die Changelogs an
  tp:
    description: Teleportiere dich zu Spielern
  tphere:
    description: Teleportiere Spieler zu dir
  tpcord:
    description: Teleportiere dich zu Coordinaten
  invsee:
    description: Schaue das Inventar von einem Spieler an
  spawn:
    description: Teleportiere dich zum Spawn
  endersee:
    description: Schaue die Enderchest von einem Spieler an
  world:
    description: Erstelle, Lösche oder bearbeite Welten
  worlds:
    description: Schaue dir die Liste aller Welten an